app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
from flask_wtf.file import FileField, FileRequired, FileAllowed
from app.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

#
class ProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Sign In')


class UploadVideoForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = StringField('Description')
    videofile = FileField('', validators=[FileRequired(), FileAllowed(['mp4', 'flv', 'mp4'])])
    submit = SubmitField('Upload')

app/users/routes.py
import os
from pathlib import Path

from werkzeug.utils import redirect, secure_filename
from app.models import User, Video
from flask import render_template, url_for, flash, request, current_app
from app import db
from app.users.forms import LoginForm, RegistrationForm, UploadVideoForm
from flask import Blueprint
from flask_login import current_user, login_user, login_required, logout_user
from app import celery

user = Blueprint('users', __name__)
from flask import jsonify
from app import create_app


@user.route('/dashboard/<username>', methods=['GET', 'POST'])
@login_required
def user_page(username):
    upload_form = UploadVideoForm()
    if upload_form.validate_on_submit():
        video_file_from_form = upload_form.videofile.data
        filename = secure_filename(video_file_from_form.filename)
        local_video_file_path = os.path.join(os.getcwd(), 'app', 'static', 'database', 'video', filename)
        video_file_path = os.path.join('/static', 'database', 'video', filename)
        try:
            os.makedirs(Path(os.path.abspath(local_video_file_path)).parent)
        except:
            pass
        video_file_from_form.save(os.path.abspath(local_video_file_path))
        video = Video(title=upload_form.title.data, description=upload_form.description.data,
                      video_path=video_file_path, user_id=current_user.id)
        video.set_video_meta_detail()
        db.session.add\
            (video)
        db.session.commit()
        flash('uploaded video')
        return redirect(url_for('users.user_page', username=current_user.username))
    return render_template('user.html', user=current_user, total_video_count=current_user.videos.count(),
                           upload_form=upload_form
                           , videos=current_user.videos)


@user.route('/qetdata', methods=['GET', 'POST'])
def request_data():
    import time

    user_id = current_user.id
    result = generate_data.delay(user_id)
    time.sleep(5)
    result_output = result.info
    result.wait(20)
    print(result.get())

    return jsonify(result.info)


@celery.task
def generate_data(user_id):
    import os
    basedir = os.path.abspath('./app')

    app = create_app()

    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL') or 'postgresql+psycopg2://skyvaib:7747@localhost/appdb'
    with app.app_context():
        id = int(user_id)
        user = User.query.filter_by(id=id).first()

        return {'videos data': [(x.video_id, x.title, x.description, x.time_of_upload, x.like, x.dislike) for x in
                                user.videos]}


@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('videos.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return render_template('login.html', title='Sign In', form=form)
        login_user(user, remember=form.remember_me.data)
        # print(user.username)
        return redirect(url_for('videos.index'))
    return render_template('login.html', title='Sign In', form=form)



@user.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('videos.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        user.set_initial_profile_pic()
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('videos.index'))


@user.route('/edit')
def edit_profile():
    new_username=request.args['user_username']
    new_email=request.args['user_email']
    chk_user=User.query.filter_by(username=new_username)
    if current_user.username != new_username:
        if chk_user:
            return jsonify({'result': 'User name already there please give any other'})


    current_user.username=new_username
    current_user.email=new_email
    db.session.commit()
    return jsonify({'result': 'changed'})

app/videos/routes.py
from datetime import datetime

from werkzeug.utils import redirect
from app.models import User, Video, Comment, VideoChange, CommentChange
from flask import render_template, url_for, flash, request, current_app, make_response, session, g, jsonify
from flask import Blueprint
from app import db
from sqlalchemy import desc
from flask_login import current_user, login_required
from app.videos.forms import CommentForm, SearchForm
video = Blueprint('videos', __name__)


def do_comment_like(to_like, comment_id):
    if not current_user.is_authenticated:
        return False

    comment = Comment.query.filter_by(comment_id=comment_id).first()
    comment_change = comment.comments_changes.filter_by(comment_change_by_user_id=int(current_user.id)).first()

    if not comment_change:
        comment_change = CommentChange(comment_change_by_user_id=int(current_user.id), comment_id=comment_id)
        db.session.add(comment_change)
    if to_like:
        if not comment_change.comment_like_change:
            comment_change.comment_like_change = True
            comment.like = comment.like + 1
            db.session.commit()
            return True
        else:
            return False
    else:
        if not comment_change.comment_dislike_change:
            comment_change.comment_dislike_change = True
            comment.dislike = comment.dislike + 1
            db.session.commit()
            return True
        else:
            return False


def do_video_like(to_like, video):


    video_id = str(video.video_id)
    if 'video_change' not in session:
        create_cookie_for_video_change(video_id, current_user.id, video)
    else:

            if video_id in session['video_change']:
                if str(current_user.id) not in session['video_change'][video_id]:
                    session['video_change'][video_id][str(current_user.id)].update({'dislike': False, 'like': False})
                if to_like:

                    if session['video_change'][video_id][str(current_user.id)]['like'] is False:

                        video.like = video.like + 1
                        # check and update in db
                        videochange = video.video_changes.filter_by(video_id=int(video_id),
                                                                    video_change_by_user_id=current_user.id).first()
                        if videochange:
                            videochange.video_like_change = True;
                            db.session.commit()
                        else:
                            videochange = VideoChange(video_id=int(video_id), video_change_by_user_id=current_user.id,
                                                      video_like_change=True)
                            db.session.add(videochange)
                            db.session.commit()

                        session['video_change'][video_id][str(current_user.id)] = {
                            'dislike': session['video_change'][video_id][str(current_user.id)]['dislike'], 'like': True}




                else:
                    if session['video_change'][video_id][str(current_user.id)]['dislike'] is False:
                        video.dislike = video.dislike + 1

                        session['video_change'][video_id][str(current_user.id)]['dislike'] = 'True'
                        # check and update in db
                        videochange = video.video_changes.filter_by(video_id=int(video_id),
                                                                    video_change_by_user_id=current_user.id).first()
                        if videochange:
                            videochange.video_dislike_change = True;
                            db.session.commit()
                        else:
                            videochange = VideoChange(video_id=int(video_id), video_change_by_user_id=current_user.id,
                                                      video_dislike_change=True)
                            db.session.add(videochange)
                            db.session.commit()

                        session['video_change'][video_id][str(current_user.id)] = {'dislike': True, 'like':
                            session['video_change'][video_id][str(current_user.id)]['like']}

                        return True

                db.session.commit()


            else:

                create_cookie_for_video_change(video_id, current_user.id, video)
    return False


@video.route('/', methods=['GET', 'POST'])
def index():
    videos = Video.query.order_by(desc(Video.number_of_views)).all()
    return render_template('index.html', videos=videos, trendings=videos[0:4])

@video.route('/like_video/<video_id>')
def like_video(video_id):
    if not current_user.is_authenticated:
        return jsonify({'error':'Please Login'})
    video = Video.query.filter_by(video_id=int(video_id)).first()

    if video:
        status=do_video_like(True, video)

        session['video_change'] = session['video_change'].copy()

        return jsonify({'status':status})
    else:
        return jsonify({'error':'video not found'})


@video.route('/dislike_video/<video_id>')
def dislike_video(video_id):
    if not current_user.is_authenticated:
        return jsonify({'error': 'Please Login'})
    video = Video.query.filter_by(video_id=int(video_id)).first()

    if video:
        status = do_video_like(False, video)

        session['video_change'] = session['video_change'].copy()

        return jsonify({'c': status})
    else:
        return jsonify({'error': 'video not found'})



@video.route('/view_video/<video_id>', methods=['GET', 'POST'])
def view_video(video_id):
    video = Video.query.filter_by(video_id=int(video_id)).first()


    commentform = CommentForm()

    # print(request.remote_addr)

    if video:
        # check value in session
        if 'video_change' in session:
            # print(session['video_change'])
            if video_id in session['video_change']:

                if current_user.is_authenticated:

                    if str(current_user.id) in session['video_change'][video_id]:

                        pass
                    else:

                        create_cookie_for_video_change(video_id,
                                                       current_user.id,
                                                       video)
                else:
                    if 'unregistered_user' in session['video_change'][video_id]:
                        pass

                    else:
                        create_cookie_for_video_change(video_id,
                                                       'unregistered_user',
                                                       video)

                # if video is already watched then skip to increase view

            else:
                create_cookie_for_video_change(video_id,
                                               current_user.id if current_user.is_authenticated else 'unregistered_user',
                                               video)

        else:
            create_cookie_for_video_change(video_id,
                                           current_user.id if current_user.is_authenticated else 'unregistered_user',
                                           video)

        #

        user_comments = User.query.join(Comment).add_columns(Comment.comment,
                                                             Comment.like, Comment.dislike,
                                                             Comment.comment_id).filter(
            User.id == Comment.user_id). \
            filter(Comment.video_id == video_id).all()

        video_uploader = User.query.filter_by(id=video.user_id).first_or_404()

        return render_template('view_video.html', video=video, user_comments=user_comments, commentform=commentform,
                               user=video_uploader)



    else:
        return 'video deleted'


def create_cookie_for_video_change(video_id, client_id, video):

    # import pdb
    # pdb.set_trace()
    add_cookie = {video_id: {client_id: {'dislike': False, 'like': False}}}
    if current_user.is_authenticated:
        video_change = VideoChange.query.filter_by(video_id=video_id, video_change_by_user_id=int(client_id)).first()

        if not video_change:
            videochange = VideoChange(video_id=video_id, video_change_by_user_id=client_id)
            db.session.add(videochange)

            video.number_of_views = video.number_of_views + 1
            video.last_view_date = datetime.utcnow()
            db.session.commit()
        else:
            add_cookie = {video_id: {
                client_id: {'dislike': video_change.video_dislike_change, 'like': video_change.video_like_change}}}
            pass
    # for new unregistered user
    else:
        video.number_of_views = video.number_of_views + 1
        video.last_view_date = datetime.utcnow()
        db.session.commit()

    if 'video_change' in session:
        temp_dict = dict(session['video_change'])
        temp_dict.update(add_cookie)
        session['video_change'] = temp_dict

    else:

        session['video_change'] = {video_id: {client_id: {'dislike': False, 'like': False}}}
    print('chanded', session['video_change'])
        # add video_id {user_id{like,dislike}} in db


@video.before_request
def initialize():
    g.search_form = SearchForm()


@video.route('/search')
def search():
    if not g.search_form.validate():
        return redirect(url_for('videos.index'))

    page = request.args.get('page', 1, type=int)
    videos, total = Video.search(g.search_form.q.data, page,
                                 current_app.config['POSTS_PER_PAGE'])

    next_url = url_for('videos.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('videos.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None

app/templates/base.html
<html lang="en">
<head>
    <script src="/static/js/jquery-3.4.1.min.js"></script>

{% import 'bootstrap/wtf.html' as wtf %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="/static/base.css">
  <link rel="icon" href="/static/img/logo.png" type="image/x-icon" />
  {% block css_import %}
  {% endblock %}
  <title>YouTube</title>
</head>
<body>
<div class="main-container">
<nav class="top-nav">
  <div class="logo">
    <a href="{{url_for('videos.index')}}"><img src="/static/img/logo.png" alt=""></a>
    <a href="{{url_for('videos.index')}}"><div class="logo-head">YOUTUBE</div></a>
  </div>
  <div class="search-bar">
{% if g.search_form %}
                <form class="navbar-form navbar-left" method="get"
                        action="{{ url_for('videos.search') }}">
                    <div class="form-group">


      {{g.search_form.q(size=140, class='form-control',
                            placeholder=g.search_form.q.label.text)}}
                    </div>
                </form>
      {%endif%}
  </div>


<!--login-->
   <div class="sign-in">
     {% if current_user.is_anonymous %}
    <label class="signed-user"></label>

    <button type="submit" name="SignIn" > <a href="{{url_for('users.login')}}">SIGN IN</a> </button>
  {% else %}
       <div   class="user-profile-image-head">
       <a href=""><img src="{{current_user.profile_pic_path}}" alt=""></a>
       </div>
       <a href="{{url_for('users.user_page',username=current_user.username)}}"><label class="signed-user">User: {{current_user.username}}</label></a>
    <button type="submit" name="SignOut"><a href="{{ url_for('users.logout') }}">Logout</a></button>
    {% endif %}
     </div>

</nav>

  {% with messages = get_flashed_messages() %}

        {% if messages %}
     <div class="alert-message">

            {% for message in messages %}
            <div>{{ message }}</div>
            {% endfor %}
            </div>
        {% endif %}

        {% endwith %}


</div>

 {% block pagecontent %}
  {% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block css_import %}
<link rel="stylesheet" href="/static/index.css">
{% endblock %}

{% block pagecontent %}
{{ moment.include_jquery() }}
{{ moment.include_moment() }}


  <div class="video-list-container">

    <div class="trending-video container">
    <div class="video-container-heading">Trending Videos</div>
    <div class="videos-container">
{% for trending in trendings%}
      <div class="video">
        <div class="video-thumb">
          <a href="{{url_for('videos.view_video',video_id=trending.video_id)}}"><img src="{{trending.video_image_thumb}}" alt=""></a>
          <div class="video-duration">{{ (trending.duration/60)|round(0, 'floor')|int }}:{{(trending.duration%60)|round(0, 'floor')|int}}</div>
        </div>
        <div class="video-title"><a href="{{url_for('videos.view_video',video_id=trending.video_id)}}">{{trending.title}}</a>
        </div>
        <div class="video-detail">
          <div class="video-user">
            <a href=""></a>
          </div>
          <div class="video-view-last-view">
            <div class="video-total-views">{{trending.number_of_views}} views</div>
            <div class="video-last-seen">{{moment(trending.last_view_date).fromNow()}}</div>
          </div>
        </div>
      </div>
 {% endfor %}



     </div>
    </div>

    <div class="all-video container">
      <div class="video-container-heading">All Videos</div>
    <div class="videos-container">
{% for video in videos %}



      <div class="video">
        <div class="video-thumb">
          <a href="{{url_for('videos.view_video',video_id=video.video_id)}}"><img src="{{video.video_image_thumb}}" alt=""></a>
          <div class="video-duration">{{ (video.duration/60)|round(0, 'floor')|int }}:{{(video.duration%60)|round(0, 'floor')|int}}</div>
        </div>
        <div class="video-title"><a href="{{url_for('videos.view_video',video_id=video.video_id)}}">{{video.title}}</a>
        </div>
        <div class="video-detail">
          <div class="video-user">
            <a href=""></a>
          </div>
          <div class="video-view-last-view">
            <div class="video-total-views">{{video.number_of_views}} views</div>
            <div class="video-last-seen">{{moment(video.last_view_date).fromNow()}}</div>
          </div>
        </div>
      </div>
 {% endfor %}


    </div>
      </div>
 {% if total==0 %}
      <div class="no-result-found">

          No result Found !!

      </div>
      {%endif%}
  </div>






{% endblock %}

app/templates/login.html
<html lang="en">
<head>


  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="./static/login.css">
  <title>Login</title>
</head>
<body>
  <div class="login-container">
    <div class="login-container_detail">
      <div>Sign IN</div>
      <div>to continue to YouTube</div>
    </div>
    <div class="login-form">
         {% if form %}
     <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
 {% endif %}
    </div>
    <div class="register_user"><a href="{{url_for('users.register') }}">CREATE ACCOUNT</a></div>
  </div>
</body>
</html>

app/templates/register.html
<html lang="en">
<head>
 {% import 'bootstrap/wtf.html' as wtf %}

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="./static/register.css">
  <title>Login</title>
</head>
<body>
  <div class="register-container">
    <div class="register-container_detail">
      <div>Sign UP</div>
      <div>to continue to YouTube</div>
    </div>
    <div class="register-form">

   <form class="form form-horizontal" method="post" role="form">

       {{ wtf.quick_form(form) }}
   </form>
    </div>
  </div>
</body>
</html>

app/templates/show_json.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JSON OUTPUT</title>
</head>
<body>

</body>
</html>

app/templates/upload.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<form action="" method="post"  enctype="multipart/form-data">>
  <input type="file" name="file"  accept="video/*" >
<input type="submit" >
</form>
</body>
</html>

app/templates/user.html
{% extends "base.html" %}

  {% block css_import %}
  <link rel="stylesheet" href="/static/user.css">
   <link rel="stylesheet" href="/static/index.css">

  {% endblock %}

{% block pagecontent %}
{{ moment.include_jquery() }}
{{ moment.include_moment() }}

<div class="user-container">
  <div class="user-container-head">Welcome</div>
  <div class="user-detail-container">
    <div class="user-profile-pic">
      <img src="{{user.profile_pic_path}}" alt="">
    </div>
    <div class="user-detail">
        <div class="user-username">UserName: <input type='text' value="{{user.username}}"   style="margin-left:5px;border:none;"></div>
      <div class="user-email"> Email: <input type='text' value="{{user.email}}"   style="margin-left:34px;border:none;"> </input>  </div>
<!--      <div class="password"> <input type='text' value="new password" disabled></input>  </div>-->


      <div class="user-total-video-count">Total Video : {{total_video_count}}</div>
      <div class="add-video">
      <span>Upload Video :</span>
{% import 'bootstrap/wtf.html' as wtf %}
        {{ wtf.quick_form(upload_form) }}

      </div>
      <div class="user-data">
     <div class="edit-profile">
            <button type="button" name="button">Edit Profile</button>
          </div>
      <button id="generatedata"  type="button">Generate Data </button>
      </div>

    </div>
  </div>
</div>

<div class="user-video">

{% if videos %}
<div class="video-list-container">
  <div class="all-video-container">
 <div class="video-container-heading">Uploaded Videos</div>
    <div class="videos-container">
    {% for video in videos%}
      <div class="video">
           <div class="video-thumb">
             <a href="{{url_for('videos.view_video',video_id=video.video_id)}}" ><img src="{{video.video_image_thumb}}" alt="{{video.title}}" ></a>
        <div class="video-duration">{{ (video.duration/60)|round(0, 'floor')|int }}:{{(video.duration%60)|round(0, 'floor')|int}}</div>
      </div>
      <div class="video-title"><a href="{{url_for('videos.view_video',video_id=video.video_id)}}">{{video.title}}</a></div>
      <div class="video-detail">

        <div class="video-view-last-view">
          <div class="video-total-views">{{video.number_of_views}} views</div>
          <div class="video-last-seen">{{moment(video.last_view_date).fromNow()}}</div>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
  </div>
</div>
  {% endif %}
</div>
<script src="/static/js/generatedata.js"></script>
<script src="/static/js/user_profile.js"></script>
{% endblock%}

app/templates/videodata.html
{% extends "base.html" %}

  {% block css_import %}
  <link rel="stylesheet" href="/static/base.css">
    <link rel="stylesheet" href="/static/view-video.css">
  {% endblock %}

{% block pagecontent %}
<h2>  </h2>
<script src="/static/js/generatedata.js"></script>
<button id="generatedata"  type="button">Generate Data </button>
{% endblock %}

app/templates/view_video.html
{% extends "base.html" %}

  {% block css_import %}
  <link rel="stylesheet" href="/static/base.css">
    <link rel="stylesheet" href="/static/view-video.css">
  {% endblock %}

{% block pagecontent %}
    <link rel="icon" href="/static/img/logo.png" type="image/x-icon" />
   <title>YouTube</title>
</head>
{% import 'bootstrap/wtf.html' as wtf %}


<div class="video-view-container">
  <div class="video-container">
    <video width="100%" controls>
    <source src="{{video.video_path}}" type="video/mp4">
  </video>
  </div>

  <div class="video-detail">
<div class="video-title">{{video.title}}</div>


    <div class="video-views-likes-dislikes">
      <div class="video-views">{{video.number_of_views}} views</div>
      <div class="video-likes-dislikes">
        <div class="video-likes">
          <form   method="post">
              <button type="submit"  formmethod="post"  name="{{video.video_id}}" value="VideoLikes" likes="{{video.like}} " >{{video.like}} Likes </button>


                  </form>

           </div>
        <div class="video-dislikes">
          <form   method="post">
             <button type="submit"  formmethod="post"  name="{{video.video_id}}" value="VideoDislikes" dislikes="{{video.dislike}}">{{video.dislike}} DisLikes </button>

                  </form>

         </div>
      </div>
    </div>
  <div class="video-user-description">
    <div class="user-name-profile-image">

      <div class="user-profile-image"><img src="{{user.profile_pic_path}}" alt=""></div>
  <a href="" class="user-name">{{user.username}}</a>
    </div>
    <div class="user-name-description">

      <div class="video-description">{{video.description}}</div>

    </div>
    <div class="video-comments-container">
      <div class="video-comments-form">
         {{ commentform.hidden_tag() }}
        {{ wtf.quick_form(commentform) }}

      </div>
  </div>
    </div>
<div class="comments-list-container">
  
</div>
    </div>
</div>
<script>var videoID={{video.video_id}}</script>
<script src="/static/js/s6.js"></script>
{% endblock %}